#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "onedark"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

# Appearence
[[custom_plugins]]
  name = "joshdick/onedark.vim"
  merged = 0

# Text Editing
[[layers]]
  name = 'foldsearch'

[[layers]]
  name = 'edit'

[[layers]]
  name = "fzf"

[[layers]]
  name = "format"

# Coding
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'checkers'

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#java"
 
# TODO: figure out java lang server
# [[layers]]
#   name = "lsp"
#   filetypes = [
#     "java"
#   ]
# 
# [layers.override_cmd]
#   java = [
#   "java",
#   "-Declipse.application=org.eclipse.jdt.ls.core.id1",
#   "-Dosgi.bundles.defaultStartLevel=4",
#   "-Declipse.product=org.eclipse.jdt.ls.core.product",
#   "-Dlog.protocol=true",
#   "-Dlog.level=NONE",
#   "-noverify",
#   "-Xmx1G",
#   "-jar",
#   "/Users/gteo/.javalsp/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar",
#   "-configuration",
#   "/Users/gteo/.javalsp/config_mac",
#   "-data",
#   "/Users/gteo/.javalsp/data"
#   ]

# Utils
[[layers]]
  name = 'git'

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "tmux"

# customizations
bootstrap_before = "myspacevim#before"
